// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENO4A7Ebms7knEtyRD1PyQDTpTqGPT1c',
    appId: '1:346527752505:web:7986c74c4fe557897648e8',
    messagingSenderId: '346527752505',
    projectId: 'bloodbankapp-1eb0e',
    authDomain: 'bloodbankapp-1eb0e.firebaseapp.com',
    databaseURL: 'https://bloodbankapp-1eb0e-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbankapp-1eb0e.appspot.com',
    measurementId: 'G-7GK9YVH908',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIjnujwXLUrS-89EzodRqTfYQzTjw87WI',
    appId: '1:346527752505:android:15a8d8e7cfe5dccf7648e8',
    messagingSenderId: '346527752505',
    projectId: 'bloodbankapp-1eb0e',
    databaseURL: 'https://bloodbankapp-1eb0e-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbankapp-1eb0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZk4pkc_D_upoXW7gqd5pv8imedBKN00',
    appId: '1:346527752505:ios:198a95174eafded47648e8',
    messagingSenderId: '346527752505',
    projectId: 'bloodbankapp-1eb0e',
    databaseURL: 'https://bloodbankapp-1eb0e-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbankapp-1eb0e.appspot.com',
    iosClientId: '346527752505-u0so2tc7mhpmnqvojgaos59feu2hnf31.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZk4pkc_D_upoXW7gqd5pv8imedBKN00',
    appId: '1:346527752505:ios:198a95174eafded47648e8',
    messagingSenderId: '346527752505',
    projectId: 'bloodbankapp-1eb0e',
    databaseURL: 'https://bloodbankapp-1eb0e-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbankapp-1eb0e.appspot.com',
    iosClientId: '346527752505-u0so2tc7mhpmnqvojgaos59feu2hnf31.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbankApp',
  );
}
